<?php

/**
 * @file
 * A light-weight, customizable lightbox plugin for jQuery 1.3
 */

use Drupal\Core\Template\Attribute;
use Drupal\Component\Serialization\Json;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;


/**
 * Prepares variables for Views isotope templates.
 *
 * Default template: views-view-isotope.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function template_preprocess_views_view_isotope(&$variables) {
  /** @var \Drupal\isotope_views\Plugin\views\style\Isotope $handler */
  $handler = $variables['view']->style_plugin;

  // Fetch wrapper classes from handler options.
  $wrapper_classes = []; #['isotope-grid'];
  if (!empty($handler->options['wrapper_class'])) {
    $wrapper_classes = array_merge($wrapper_classes, explode(' ', $handler->options['wrapper_class']));
    $wrapper_classes = array_map('\Drupal\Component\Utility\Html::cleanCssIdentifier', $wrapper_classes);
  }
  $variables['attributes'] = new Attribute(array('class' => $wrapper_classes));
  $variables['#attached']['library'][] = 'isotope_views/isotope_views';

  template_preprocess_views_view_unformatted($variables);
}
